# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

replicaCount: 1
logLevel: "debug"

image:
  repository: quay.io/ibmgaragecloud/inventory-svc-kafka
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

volumes:
  name: messagingConfig

configMap:
  name: messaging-broker-config

route:
  enabled: true

ingress:
  enabled: false
  appid:
    enabled: false
    # web or app - https://cloud.ibm.com/docs/services/appid?topic=appid-kube-auth
    requestType: web

#  host: hello
  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""

messageConfig:
  clientId: "inventory-service-client"
  kafka_topic: "testTopic-3"
  brokers: "192.168.50.11:9092"
  connectionTimeout: "3000"
  authenticationTimeout: "1000"
  reauthenticationThreshold: "10000"
  retries: "3"
  maxRetryTime: "5"

vcsInfo:
  repoUrl: ""
  branch: ""

partOf: ""

connectsTo: ""

runtime: ""