apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node-deployment
  namespace: dev
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: nodejs-pod
        image: quay.io/ibmgaragecloud/inventory-svc-kafka:dev
        resources:
          limits:
            memory: "1Gi"
            cpu: "200m"
          requests:
            memory: "256Mi"
            cpu: "5m"
        ports:
          - containerPort: 3000
            name: http
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/app/src/env/confluent-kafka-cert"
            name: kafka-sasl-key
            readOnly: true
          - mountPath: "/app/src/env/kafka-operator-key"
            name: kafka-operator-key
            readOnly: true
      volumes:
        - name: kafka-sasl-key
          secret:
            secretName: confluent-kafka-cert
        - name: kafka-operator-key
          secret:
            secretName: kafka-operator-key
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: test-kafka
spec:
  to:
    kind: Service
    name: test-service
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None