apiVersion: v1
kind: Pod
metadata:
  name: test-node-pod
  labels:
    app: kafka
spec:
  containers:
    - name: nodejs-pod
      image: quay.io/ibmgaragecloud/inventory-svc-kafka:1.0.2
      ports:
      - containerPort: 3000
        name: http
      imagePullPolicy: Always