apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app: kafka
